### ISSUE TITLE
Reverse unixtime

### ISSUE THREAD

**Issue by fossdd** [schoenenberg/unixtime#3]
Hey, here a small feature request.

I recently wanted to get unixtime's into a usual date format (like [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.8)).

In `date` I do:
```
$ date --date=@1458647617
Tue Mar 22 11:53:37 AM UTC 2016
```

But I often forget it, and I think it's a nice addition to your unixtime binary.

**Comment by schoenenberg** [comment]
Hi @fossdd,

I like that idea! But if we do this, we need to keep also the `--millis` and `--nanos` option in mind. Maybe something like `--from-millis` and `--from-nanos`.

Also I would prefer to keep time zones and custom date formats out of scope for this utility. Otherwise we can just rewrite the `date` utility in Rust. Maybe only support for RFC 2822 and RFC 3339!?

@fossdd Do you have some time to do a PR?

**Comment by fossdd** [comment]
> I like that idea! But if we do this, we need to keep also the `--millis` and `--nanos` option in mind. Maybe something like `--from-millis` and `--from-nanos`.

Yes, I think this is fine.

> Also I would prefer to keep time zones and custom date formats out of scope for this utility. Otherwise we can just rewrite the `date` utility in Rust. Maybe only support for RFC 2822 and RFC 3339!?

I have to look into it, but of course.

> @fossdd Do you have some time to do a PR?

A bit, if it doesn't bring too much errors :-)

**Comment by schoenenberg** [comment]
@fossdd Thank you very much for your PR!

I thought about it as well and did an implementation myself (#5). What do you think?

**Comment by schoenenberg** [comment]
@fossdd Released in version 0.2.0
